export const FinanceBarLinks = [
  { href: "/", key: "Target Circle", text: "Target Circle" },
  { href: "/", key: "Target Circle Card", text: "Target Circle Card" },
  { href: "/", key: "Target Circle 360", text: "Target Circle 360" },
  { href: "/", key: "Registry", text: "Registry" },
  { href: "/", key: "Weekly Ad", text: "Weekly Ad" },
  { href: "/", key: "Find Stores", text: "Find Stores" },
];

export const NavBarLinks = [
  {
    key: "Categories",
    text: "Categories",
    children: [
      { href: "/", text: "Back to School" },
      { href: "/", text: "College" },
      { href: "/", text: "Grocery" },
      { href: "/", text: "Clothing, Shoes & Accessories" },
      { href: "/", text: "Home" },
      { href: "/", text: "Outdoor Living & Garden" },
      { href: "/", text: "Furniture" },
      { href: "/", text: "Kitchen & Dining" },
      { href: "/", text: "Electronics" },
      { href: "/", text: "Video Games" },
      { href: "/", text: "Toys" },
      { href: "/", text: "Sports & Outdoors" },
      { href: "/", text: "Movies, Music & Books" },
      { href: "/", text: "Baby" },
      { href: "/", text: "Household Essentials" },
      { href: "/", text: "Beauty" },
      { href: "/", text: "Ulta Beauty at Target" },
      { href: "/", text: "Personal Care" },
      { href: "/", text: "Health" },
      { href: "/", text: "Pets" },
      { href: "/", text: "School & Office Supplies" },
      { href: "/", text: "Arts, Crafts & Sewing" },
      { href: "/", text: "Party Supplies" },
      { href: "/", text: "Luggage" },
      { href: "/", text: "Halloween" },
      { href: "/", text: "Gift Ideas" },
      { href: "/", text: "Gift Cards" },
      { href: "/", text: "Character Shop" },
      { href: "/", text: "Bullseye's Playground" },
      { href: "/", text: "Clearance" },
    ],
  },
  {
    key: "Deals",
    text: "Deals",
    children: [
      { href: "/", text: "Top Deals" },
      { href: "/", text: "Target Circle Deals" },
      { href: "/", text: "Weekly Ad" },
      { href: "/", text: "Clearance" },
    ],
  },
  {
    key: "New & featured",
    text: "New & featured",
    children: [
      { href: "/", text: "Target New Arrivals" },
      { href: "/", text: "Target Finds" },
      { href: "/", text: "#TargetStyle" },
      { href: "/", text: "Black Beyond Measure" },
      { href: "/", text: "Más Que" },
      { href: "/", text: "Women-Owned Brands at Target" },
      { href: "/", text: "Asian-Owned Brands at Target" },
      { href: "/", text: "LGBTQIA+ Shop" },
    ],
  },
  {
    key: "Pickup & delivery",
    text: "Pickup & delivery",
    children: [
      { href: "/", text: "Shop Order Pickup" },
      { href: "/", text: "Shop Same Day Delivery" },
    ],
  },
];
